package com.common.type;

import java.io.Serializable;

public enum TypeCode implements Serializable
{
	GENDER, ADDRESSTYPE,CONTACTTYPE,SUPPORT_STATUS,USER_ROLE,
	MAIN_CITY_TYPE,CAPE_TOWN_TYPE, DURBAN_TYPE, JOHANNESBURG_TYPE, PRETORIA_TYPE,
	Other_Towns_And_Cities, ACTIVATION_STATUS_TYPE, VENUE_TYPE, SYSTEM_TYPE, IMAGE_STATUS,REGISTRATION_STATUS_TYPE
}